import { Router } from 'express';
import { RevisionController } from '../controllers/RevisionController.js';
import { asyncHandler } from '../http/asyncHandler.js';
import { requireAuth } from '../middleware/authMiddleware.js';
const controller = new RevisionController();
export const revisionRoutes = Router();
revisionRoutes.use(requireAuth);
revisionRoutes.get('/:projectId/snapshots', asyncHandler(controller.listSnapshots));
revisionRoutes.post('/:projectId/snapshots', asyncHandler(controller.createSnapshot));
revisionRoutes.post('/:projectId/snapshots/compare', asyncHandler(controller.compareSnapshots));
revisionRoutes.get('/:projectId/snapshots/:snapshotId', asyncHandler(controller.getSnapshot));
revisionRoutes.delete('/:projectId/snapshots/:snapshotId', asyncHandler(controller.deleteSnapshot));
revisionRoutes.post('/:projectId/snapshots/:snapshotId/restore', asyncHandler(controller.restoreSnapshot));
revisionRoutes.post('/:projectId/snapshots/:snapshotId/branch', asyncHandler(controller.branchSnapshot));
revisionRoutes.get('/:projectId/annotations', asyncHandler(controller.listAnnotations));
revisionRoutes.post('/:projectId/annotations', asyncHandler(controller.createAnnotation));
revisionRoutes.get('/:projectId/annotations/:threadId', asyncHandler(controller.getAnnotation));
revisionRoutes.post('/:projectId/annotations/:threadId/replies', asyncHandler(controller.replyAnnotation));
revisionRoutes.post('/:projectId/annotations/:threadId/resolve', asyncHandler(controller.resolveAnnotation));
revisionRoutes.post('/:projectId/annotations/:threadId/reopen', asyncHandler(controller.reopenAnnotation));
revisionRoutes.post('/:projectId/annotations/:threadId/accept', asyncHandler(controller.acceptSuggestion));
revisionRoutes.post('/:projectId/annotations/:threadId/reject', asyncHandler(controller.rejectSuggestion));
