/**
 * Regenerates the opentales-tools skill's tool reference from the live tool
 * schemas so the documentation cannot drift from the implementation.
 *
 *   pnpm exec tsx scripts/generate-opentales-tool-reference.ts
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { toolManifest } from '../src/useCases/ai/opencode/toolManifest.js';
import { agentMutatingToolNames } from '../src/useCases/ai/tools/index.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = resolve(root, 'src/useCases/ai/skills/opentales-tools/references/tool-reference.md');
const mutating = new Set<string>(agentMutatingToolNames);
const tools = toolManifest({} as never, 'reference', 'reference').sort((a, b) => a.name.localeCompare(b.name));

type Schema = { type?: string | string[]; properties?: Record<string, Schema>; required?: string[]; enum?: unknown[]; items?: Schema; description?: string; anyOf?: Schema[] };

function typeOf(schema: Schema | undefined): string {
  if (!schema) return 'any';
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(' \\| ');
  if (schema.anyOf) return schema.anyOf.map(typeOf).join(' \\| ');
  const type = Array.isArray(schema.type) ? schema.type.join(' \\| ') : schema.type;
  if (type === 'array') return `${typeOf(schema.items)}[]`;
  return type ?? 'object';
}

const section = (title: string, list: typeof tools) => [
  `## ${title}`,
  '',
  ...list.flatMap((tool) => {
    const schema = tool.inputSchema as Schema;
    const required = new Set(schema.required ?? []);
    const props = Object.entries(schema.properties ?? {});
    return [
      `### \`${tool.name}\``,
      '',
      tool.description.replace(/ The user will approve\/reject the proposal in the UI\.?/g, '').replace(/^\w+: /, ''),
      '',
      props.length
        ? ['| Field | Type | Required |', '| --- | --- | --- |', ...props.map(([name, prop]) => `| \`${name}\` | ${typeOf(prop)} | ${required.has(name) ? 'yes' : ''} |`)].join('\n')
        : '_No input._',
      ''
    ];
  })
];

const body = [
  '# OpenTales tool reference',
  '',
  '<!-- Generated by scripts/generate-opentales-tool-reference.ts. Do not edit by hand. -->',
  '',
  'Read tools run immediately. Change tools are proposals in Manual mode and apply immediately in Auto mode.',
  '',
  '## Contents',
  '',
  '- [Read tools](#read-tools)',
  '- [Change tools](#change-tools)',
  '',
  ...section('Read tools', tools.filter((tool) => !mutating.has(tool.name))),
  ...section('Change tools', tools.filter((tool) => mutating.has(tool.name)))
].join('\n');

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, `${body.trimEnd()}\n`);
console.log(`Wrote ${tools.length} tools to ${target}`);
